"""Creacion de la tabla mascotas

Revision ID: 6166dcb56327
Revises: 2299ce6e465d
Create Date: 2023-08-08 16:47:39.643207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6166dcb56327'
down_revision = '2299ce6e465d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('Perro', 'Gato', 'Cuy', name='tipodemascota'), nullable=False),
    sa.Column('sexo', sa.Enum('Macho', 'Hembra', 'Helicoptero', 'Otro', name='sexomascota'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    # ### end Alembic commands ###
